baseURL = "https://blacktop.github.io/ipsw/"
languageCode = "en-us"
title = "ipsw"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Docs"
url = "/docs/"
weight = 2

[[menu.main]]
name = "Github"
url = "https://github.com/blacktop/ipsw"
weight = 3

[params]
google_analytics_id = ""
homepage_button_link = '/ipsw/docs'
homepage_button_text = 'Read The Docs'
homepage_intro = 'Download and parse iOS ipsws.'
homepage_image = '/ipsw/images/ipsw.gif'
#homepage_image = '/images/terminal.svg'

## You can enable to add anchor links to header elements
# enable_anchor_link = true

[params.homepage_meta_tags]
meta_description = "Download and parse iOS ipsws."
meta_og_title = "ipsw"
meta_og_type = "tool"
meta_og_url = "https://blacktop.github.io/ipsw/"
meta_og_image = "https://github.com/blacktop/ipsw/raw/master/docs/static/images/ipsw.png"
meta_og_description = "We build tools that automate things."
meta_twitter_card = "summary"
meta_twitter_site = "@blacktop__"
meta_twitter_creator = "@blacktop__"

[params.logo]
mobile = "/ipsw/images/ipsw.png"
standard = "/ipsw/images/ipsw.png"
